spring.application.name=freya
spring.datasource.url=jdbc:mysql://localhost:3306/freya
spring.datasource.username=root
spring.datasource.password=root

# borrar la bdd, levantar seed de resources/data.sql
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
